[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn", "python311", "postgresql"]

[phases.install]
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  "yarn workspace @workspace/dtf-pliego build",
  "yarn workspace @workspace/api-server build"
]

[start]
cmd = "bash /app/railway-start.sh"
